"""Build script for tree-sitter-kedi.

The C extension `tree_sitter_kedi._binding` is compiled from:

  - src/parser.c     — generated by `tree-sitter generate` from grammar.js
  - src/scanner.c    — hand-written external scanner (indent stack,
                       fenced-body raw-byte scanner, TEXT / TEXT_IN_CALL)
  - bindings/python/tree_sitter_kedi/binding.c — PyCapsule wrapper for the
                       `tree_sitter_kedi()` symbol exported by parser.c

Project metadata lives in pyproject.toml; this file only carries the
extension declaration (which pyproject.toml currently doesn't ergonomically
support as a single TOML stanza).
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:

    class Extension:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def setup(*args: Any, **kwargs: Any) -> None: ...
else:
    from setuptools import Extension, setup

setup(
    ext_modules=[
        Extension(
            name="tree_sitter_kedi._binding",
            sources=[
                "bindings/python/tree_sitter_kedi/binding.c",
                "src/parser.c",
                "src/scanner.c",
            ],
            include_dirs=["src"],
            # Match the warning settings the tree-sitter CLI uses when
            # compiling parser.c so we don't surface noise on user installs.
            extra_compile_args=[
                "-std=c11",
                "-fPIC",
            ],
        ),
    ],
)
